### ISSUE TITLE
使用金苹果无法恢复最大生命值

### ISSUE THREAD

**Issue by PrzemyslvonWhite** [Viola-Siemens/Hardcore-Reborn#1]
[latest.log](https://github.com/user-attachments/files/16915220/latest.log)

**Comment by Viola-Siemens** [comment]
日志里并没有相关报错，猜测程序正常执行而用户未搞清楚实际功能。每个金苹果只有11%概率恢复最大生命值，如果一个不能成功请多试几次。

**Comment by PrzemyslvonWhite** [comment]
> 日志里并没有相关报错，猜测程序正常执行而用户未搞清楚实际功能。每个金苹果只有11%概率恢复最大生命值，如果一个不能成功请多试几次。

一共食用了一组金苹果和一组附魔金苹果，均没有生效

**Comment by Viola-Siemens** [comment]
> [14:59:16] [Render thread/ERROR]: Failed to load function hardcore_reborn:gain_health
> java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 3: 错误的命令参数 at position 71: ...andom run <--[HERE]
> 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
> 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
> Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 3: 错误的命令参数 at position 71: ...andom run <--[HERE]
> 	at net.minecraft.commands.CommandFunction.m_77984_(CommandFunction.java:63) ~[client-1.20.1-20230612.114412-srg.jar%23734!/:?]
> 	at net.minecraft.server.ServerFunctionLibrary.m_214320_(ServerFunctionLibrary.java:83) ~[client-1.20.1-20230612.114412-srg.jar%23734!/:?]
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
> 	... 6 more

我找到了金苹果无法生效的原因了，random命令是1.20.2加入的，更早的版本无法模拟随机数，所以无法在1.20.1里使用。但附魔金苹果应该不受影响才对，你确定尝试过附魔金苹果吗

**Comment by PrzemyslvonWhite** [comment]
> > [14：59：16] [渲染线程/错误]：无法加载函数 hardcore_reborn：gain_health java.util.concurrent.CompletionException：java.lang.IllegalArgumentException：在第 3 行解析命令时：在位置 71 处有错误的命令参数：...andom run <--[HERE] at java.util.concurrent.CompletableFuture.encodeThrowable（CompletableFuture.java：315） ~[？：？]在 java.util.concurrent.CompletableFuture.completeThrowable（CompletableFuture.java：320） ~[？：？]在 java.util.concurrent.CompletableFuture$AsyncSupply.run（CompletableFuture.java：1770） ~[？：？]在 java.util.concurrent.CompletableFuture$AsyncSupply.exec（CompletableFuture.java：1760） ~[？：？]在 java.util.concurrent.ForkJoinTask.doExec（ForkJoinTask.java：387） ~[？：？]在 java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec（ForkJoinPool.java：1312） ~[？：？]在 java.util.concurrent.ForkJoinPool.scan（ForkJoinPool.java：1843） ~[？：？]在 java.util.concurrent.ForkJoinPool.runWorker（ForkJoinPool.java：1808） ~[？：？]在 java.util.concurrent.ForkJoinWorkerThread.run（ForkJoinWorkerThread.java：188） ~[？：？]原因：java.lang.IllegalArgumentException：在第 3 行解析命令时：在位置 71 处有错误的命令参数：...andom run <--[HERE] at net.minecraft.commands.CommandFunction.m_77984_（CommandFunction.java：63） ~[client-1.20.1-20230612.114412-srg.jar%23734！/：？] at net.minecraft.server.ServerFunctionLibrary.m_214320_（ServerFunctionLibrary.java：83） ~[client-1.20.1-20230612.114412-srg.jar%23734！/：？]在 java.util.concurrent.CompletableFuture$AsyncSupply.run（CompletableFuture.java：1768） ~[？：？] ...6 更多
> 
> 我找到了金苹果无法生效的原因了，random命令是1.20.2加入的，更早的版本无法模拟随机数，所以无法在1.20.1里使用。但附魔金苹果应该不受影响才对，你确定尝试过附魔金苹果吗

我十分确定，一共食用了一组的附魔金苹果和金苹果，均无法生效
